
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: project
spec:
  selector:
    matchLabels:
      app: project
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name:  project
          image: localhost:5000/project
          ports:
            - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name:  project
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: project